Modules/DomainHosting/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::prefix('domainhosting')->group(function() {
//    Route::get('/', 'DomainHostingController@index');
//});

//Route for domain-hosting starts here


use Modules\DomainHosting\Http\Controllers\DomainHostingController;

Route::group(['middleware'=>'auth','prefix'=>'admin'],function () {

    Route::get('domain-hosting', [DomainHostingController::class, 'index'])->name('domain-hosting');
    //route for provider
    Route::resource('provider', ProviderController::class);
    //route for domain
    Route::resource('domain', DomainController::class);
    //route for hosting
    Route::resource('hosting', HostingController::class);
    //route for customer
    Route::resource('customer', CustomerController::class);
    //route for customer search
    Route::post('customer-search', [CustomerController::class, 'search'])->name('customer.search');
    //route for customer hosting
    Route::resource('customer-hosting', CustomerHostingController::class);
    Route::put('customer-hosting/check-status/{id}', [CustomerHostingController::class, 'status']);
    //route for customer domain
    Route::resource('customer-domain', CustomerDomainController::class);
    Route::put('customer-domain/check-status/{id}', [CustomerDomainController::class, 'status']);
    //route for name server
    Route::resource('name-server', NameServerController::class);
    Route::put('name-server/check-status/{id}', [NameServerController::class, 'status']);
    //route for renews
    Route::resource('renew', RenewController::class);
    //Route for domain-hosting ends here
});

Modules/DomainHosting/Resources/views/includes/footer.blade.php
<footer class="main-footer">
    <strong>Copyright &copy; 2021-2022 <a href="https://adminlte.io">Web Point Limited</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.1.0
    </div>
  </footer>

Modules/DomainHosting/Resources/views/includes/left-side-nav.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <a href="index3.html" class="brand-link">
        <img src="{{ asset('lte/dist/img/logo.png') }}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
            style="opacity: .8">
        <span class="brand-text font-weight-light">{{ __('Domain & Hosting') }}</span>
    </a>
    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{ asset('lte/dist/img/user2-160x160.jpg') }}" class="img-circle elevation-2"
                    alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">{{ Auth::user()->name }}</a>
            </div>
        </div>
        <div class="form-inline">
            <div class="input-group" data-widget="sidebar-search">
                <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-sidebar">
                        <i class="fas fa-search fa-fw"></i>
                    </button>
                </div>
            </div>
        </div>
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item ">
                    <a href="{{ url('') }}" class="nav-link {{ isMenuActive('admin/domain-hosting') }}">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>{{ __('Dashboard') }}</p>
                    </a>
                </li>
                <li class="nav-item  {{ isMenuActive(['admin/domain','admin/customer-domain']) }}">
                    <a href="javascript:" class="nav-link {{ isMenuActive(['admin/domain','admin/customer-domain']) }}">
                        <i class="nav-icon fas fa-database"></i>
                        <p>
                            {{ __(' Domain Management')}}
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{ route('domain.index') }}" class="nav-link {{ isMenuActive('admin/domain') }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>{{ __('Domains')}}</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('customer-domain.index') }}"
                                class="nav-link {{ isMenuActive('admin/customer-domain') }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>{{ __('Customers')}}</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item  {{ isMenuActive(['admin/hosting*','admin/name-server*','admin/customer-hosting']) }}">
                    <a href="javascript:"
                        class="nav-link {{ isMenuActive(['admin/hosting*','admin/name-server*','admin/customer-hosting']) }}">
                        <i class="nav-icon fas fa-cloud"></i>
                        <p>
                            {{ __('Hosting Management')}}
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{ route('hosting.index') }}" class="nav-link {{ isMenuActive('admin/hosting') }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>{{ __('Hosting')}}</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('customer-hosting.index') }}"
                                class="nav-link  {{ isMenuActive('admin/customer-hosting') }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>{{ __('Customers')}}</p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="{{ route('name-server.index') }}"
                                class="nav-link  {{ isMenuActive('admin/name-server') }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>{{ __('Name Server')}}</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item  {{ isMenuActive(['admin/provider*','admin/customer']) }}">
                    <a href="javascript:"
                        class="nav-link {{ isMenuActive(['admin/provider*','admin/customer']) }}">
                        <i class="nav-icon fas fa-cogs"></i>
                        <p>
                            {{ __('Contact Info')}}
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{ route('provider.index') }}"
                                class="nav-link  {{ isMenuActive('admin/provider') }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>{{ __('Providers')}}</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('customer.index') }}"
                                class="nav-link {{ isMenuActive('admin/customer') }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>{{ __('Customers')}}</p>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</aside>

Modules/DomainHosting/Resources/views/includes/top-nav.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-bell"></i>
                <span class="badge badge-warning navbar-badge">{{count(domainNotification())}}</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-item dropdown-header">Notifications</span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <p>
                        <b>
                            @foreach(domainNotification() as $domain)
                              {{$domain->name}} will be expired on {{$domain->expire_date}}
                            @endforeach
                        </b>
                    </p>
                </a>
            </div>
        </li>
        <!-- Messages Dropdown Menu -->

        <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                <i class="fas fa-th-large"></i>
            </a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-user"></i>
                <span class="badge badge-danger navbar-badge">1</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <a class="dropdown-item" href="{{route('home')}}">Back to App List</a>
                <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                         document.getElementById('logout-form').submit();">
                    {{ __('Logout') }}
                </a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                    @csrf
                </form>
            </div>
        </li>
    </ul>
</nav>