Modules/DomainHosting/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::prefix('domainhosting')->group(function() {
//    Route::get('/', 'DomainHostingController@index');
//});

//Route for domain-hosting starts here


use Modules\DomainHosting\Http\Controllers\DomainHostingController;

Route::group(['middleware'=>'auth','prefix'=>'admin'],function () {

    Route::get('domain-hosting', [DomainHostingController::class, 'index'])->name('domain-hosting');
    //route for provider
    Route::resource('provider', ProviderController::class);
    //route for domain
    Route::resource('domain', DomainController::class);
    //route for hosting
    Route::resource('hosting', HostingController::class);
    //route for customer
    Route::resource('customer', CustomerController::class);
    //route for customer search
    Route::post('customer-search', [CustomerController::class, 'search'])->name('customer.search');
    //route for customer hosting
    Route::resource('customer-hosting', CustomerHostingController::class);
    Route::put('customer-hosting/check-status/{id}', [CustomerHostingController::class, 'status']);
    //route for customer domain
    Route::resource('customer-domain', CustomerDomainController::class);
    Route::put('customer-domain/check-status/{id}', [CustomerDomainController::class, 'status']);
    //route for name server
    Route::resource('name-server', NameServerController::class);
    Route::put('name-server/check-status/{id}', [NameServerController::class, 'status']);
    //route for renews
    Route::resource('renew', RenewController::class);
    //Route for domain-hosting ends here
});

Modules/DomainHosting/Entities/NameServer.php
<?php

namespace Modules\DomainHosting\Entities;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class NameServer extends Model
{
    use HasFactory;

    protected $fillable = ['name','ip','is_active'];
}

Modules/DomainHosting/Http/Controllers/NameServerController.php
<?php

namespace Modules\DomainHosting\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Modules\DomainHosting\Entities\NameServer;

class NameServerController extends Controller
{
    public function index()
    {
        $nameServer = NameServer::query()->paginate(10);
        return view('domainhosting::nameServer.index',compact('nameServer'));
    }

    public function create()
    {
        return view('domainhosting::nameServer.add');
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(),[
            'name' => 'required',
            'ip' => 'required',
            'is_active' => 'required'
        ]);

        if($validator->fails()){
            return redirect()->back()->withErrors($validator)->withInput($request->all());
        }

        NameServer::query()->create($request->all());
        return redirect('admin/name-server')->with('success', 'Name Server added Successfully!');
    }

    public function edit($id)
    {
        $nameServer= NameServer::query()->findOrFail($id);
        return view('domainhosting::nameServer.edit',compact('nameServer'));
    }

    public function update($id, Request $request)
    {
        $validator = Validator::make($request->all(),[
            'name' => 'required',
            'ip' => 'required',
            'is_active' => 'required'
        ]);
        $nameServer = NameServer::query()->findOrFail($id);

        if($validator->fails()){
            return redirect()->back()->withErrors($validator)->withInput($request->all());
        }

        $nameServer->update($request->all());
        return redirect('admin/name-server')->with('success', 'Name Server Updated Successfully!');
    }

    public function destroy($id)
    {
        $nameServer = NameServer::query()->findOrFail($id);
        $nameServer->delete();
        return redirect('admin/name-server')->with('success', 'Name Server Deleted Successfully!');
    }

    public function status($id): \Illuminate\Http\RedirectResponse
    {

        $nameServer = NameServer::query()->findOrFail($id);
        if($nameServer->is_active == 1)
        {
            $nameServer->is_active = 0;
        }else{
            $nameServer->is_active = 1;
        }
        $nameServer->save();

        return redirect('admin/name-server')->with('success','Status Changed Successfully');
    }
}

Modules/DomainHosting/Resources/views/nameServer/add.blade.php
@extends('domainhosting::layouts.master')

@section('title','Name Server')

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h3>{{ __('Add New Name Server') }}</h3>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">{{ __('Settings') }}</a></li>
                        <li class="breadcrumb-item active">{{__ ('Name Server') }}</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <section class="content">
        @if($errors->any())
            <ul>
                @foreach($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        @endif
    </section>

    <!-- ***/Notices page inner Content Start-->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            {{ Form::model($nameServer = new \Modules\DomainHosting\Entities\NameServer,['url'=>'admin/name-server','method'=>'post']) }}
                            @include('domainhosting::nameServer.form')
                            {{ Form::close() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@stop

Modules/DomainHosting/Resources/views/nameServer/edit.blade.php
@extends('domainhosting::layouts.master')

@section('title','Edit Name Server')

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{__('Edit Name Server')}}</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">{{__('Settings')}}</a></li>
                        <li class="breadcrumb-item active">{{__('Edit Name Server')}}</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <section class="content">
        @if($errors->any())
            <ul>
                @foreach($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        @endif
    </section>

    <!-- ***/Notices page inner Content Start-->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            {{ Form::model($nameServer,['route'=>['name-server.update',$nameServer->id],'method'=>'patch']) }}
                            @include('domainhosting::nameServer.form')
                            {{ Form::close() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@stop

Modules/DomainHosting/Resources/views/nameServer/form.blade.php
<div class="row">
    <div class="col-6">
        <div class="form-group">
            <label for="name">Name*:</label>
            {{ Form::text('name',null,['class'=>'form-control','placeholder'=>'Enter Name Here:']) }}
        <small class="text-danger">{{ $errors->first('name') }}</small>
        </div>
    </div>
    <div class="col-6">
        <div class="form-group">
            <label for="ip">IP*:</label>
            {{ Form::text('ip',null,['class'=>'form-control','placeholder'=>'Enter IP Here:']) }}
        <small class="text-danger">{{ $errors->first('ip') }}</small>
        </div>
    </div>
</div>

<div class="col">
    <div class="form-group">
        <label for="is_active">Is active*:</label>
        <input type="checkbox" name="is_active" value="1" class="flat-red" {{ $nameServer->is_active == 1 ? 'checked' : '' }}>
    </div>
</div>

<div class="col">
    <button type="submit" class="btn btn-success" > Create</button>
    <a href="{{ URL::previous() }}" class="btn btn-danger">Cancel</a>
</div>


    @section('script')
        <script>
            $(function () {
                $('.select2').select2();
            });
        </script>
@stop

Modules/DomainHosting/Resources/views/nameServer/index.blade.php
@extends('domainhosting::layouts.master')

@section('title','Name Server')

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{__('Name Server')}}</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">{{ __('Settings') }}</a></li>
                        <li class="breadcrumb-item active">{{__('Name Server')}}</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>


    <!-- ***/Chart of Accounts page inner Content Start-->
    <section class="content">
        <div class="container-fluid">
            @if (session('status'))
                <div class="alert alert-success">
                    {{ session('status') }}
                </div>
            @endif
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header" style="border-bottom: none !important;">
                            <div class="row">
                                <div>
                                    <a href="{{ url('admin/name-server/create') }}" class="btn btn-info btn-sm" style="margin-top: 10px; margin-left: 10px;"> <i class="fas fa-plus-circle"></i> New</a>
                                </div>
                            </div>
                        </div>

                        <div class="card-body">
                            <div class="table-responsive">
                                <table id="example2" class="table table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th>{{ __('Sl') }}</th>
                                        <th>{{ __('Name') }}</th>
                                        <th>{{ __('ip') }}</th>
                                        <th>{{ __('Status') }}</th>
                                        <th>{{ __('Action') }}</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($nameServer as $key => $data)
                                        <tr>
                                            <td>{{ $key+1 }}</td>
                                            <td>{{ $data->name }}</td>
                                            <td>{{ $data->ip }}</td>
                                            <td>
                                                {{ Form::open(['method'=>'PUT','url'=>['admin/name-server/check-status/'.$data->id],'style'=>'display:inline']) }}
                                                @if($data->is_active == 1)
                                                    {{ Form::submit('Active',['class'=>'btn btn-success btn-sm']) }}
                                                @else
                                                    {{ Form::submit('In Active',['class'=>'btn btn-danger btn-sm']) }}
                                                @endif
                                                {{ Form::close() }}
                                            </td>
                                            <td>
                                                {{ Form::open(['url'=>['admin/name-server',$data->id],'method'=>'delete','onsubmit'=>'return confirmDelete()']) }}
                                                <a href="{{ route('name-server.edit',$data->id) }}" class="btn btn-warning btn-sm"><i class="fas fa-edit"></i></a>
                                                <button type="submit" class="btn btn-danger btn-sm"><i class="fas fa-trash"></i></button>
                                                {{ Form::close() }}
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>

                            </div>
                            <div class="row" style="margin-top: 10px">
                                <div class="col-sm-12 col-md-9">
                                    {{-- <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">Showing 0 to 0 of 0 entries</div> --}}
                                </div>
                                <div class="col-sm-12 col-md-3">
                                    {{ $nameServer->links() }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

@stop

@section('script')
    <script>
        function confirmDelete(){
            let x = confirm('Are you sure you want to delete this account head?');
            return !!x;
        }
    </script>
@stop