Modules/SmsGateway/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::prefix('smsgateway')->group(function() {
//    Route::get('/', 'SmsGatewayController@index');
//});

use Modules\SmsGateway\Http\Controllers\ContactGroupController;
use Modules\SmsGateway\Http\Controllers\CustomSmsController;
use Modules\SmsGateway\Http\Controllers\EmployeeContactController;

Route::prefix('admin')->middleware(['auth', 'verified'])->group(function () {
// Custom Sms
//    Route::resource('custom-sms',CustomSmsController::class);
    Route::get('custom-sms', [CustomSmsController::class, 'index'])->name('customSms.index');
    Route::get('custom-sms/create', [CustomSmsController::class, 'create'])->name('customSms.create');
    Route::post('custom-sms/store', [CustomSmsController::class, 'store'])->name('customSms.store');
//// Custom Sms

// Contacts
    Route::resource('contact', ContactController::class);
    Route::post('contact-search', [ContactController::class, 'search'])->name('contact.search');
    Route::get('employee-contact', [EmployeeContactController::class, 'index'])->name('employeeContact.index');
    Route::post('employee-sms', [EmployeeContactController::class, 'sms'])->name('employeeContact.sms');
// Contacts

// Contact Group
    Route::get('contact-group', [ContactGroupController::class, 'index'])->name('contactGroup.index');
    Route::get('contact-group/create', [ContactGroupController::class, 'create'])->name('contactGroup.create');
    Route::post('contact-group', [ContactGroupController::class, 'store'])->name('contactGroup.store');
    Route::put('contact-group/{contactGroup}', [ContactGroupController::class, 'update'])->name('contactGroup.update');
    Route::delete('contact-group/{contactGroup}', [ContactGroupController::class, 'destroy'])->name('contactGroup.destroy');
    Route::get('contact-group/{contactGroup}/edit', [ContactGroupController::class, 'edit'])->name('contactGroup.edit');
    Route::get('contact-group/{contactGroup}/show', [ContactGroupController::class, 'show'])->name('contactGroup.show');
// Contact Group
});

Modules/SmsGateway/Entities/ContactGroup.php
<?php

namespace Modules\SmsGateway\Entities;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ContactGroup extends Model
{
    use HasFactory;
    protected $fillable = [
        'name',
    ];

    public function contacts()
    {
        return $this->hasMany(Contact::class);
    }
}

Modules/SmsGateway/Http/Controllers/ContactGroupController.php
<?php

namespace Modules\SmsGateway\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Modules\SmsGateway\Entities\ContactGroup;

class ContactGroupController extends Controller
{
    public function index()
    {   
        
        $contactGroups = ContactGroup::query()->withCount(['contacts'])->paginate(10);
        // dd($contactGroups);
        return view('smsgateway::contactGroup.index',compact('contactGroups'));
    }

    public function create()
    {
        return view('smsgateway::contactGroup.add');
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(),[
            'name'      => 'required|string',
        ]);

        if($validator->fails()){
            return redirect()->back()->withErrors($validator)->withInput($request->all());
        }
        
        ContactGroup::query()->create($request->all());
        return redirect()->route('contactGroup.index')->with('success', 'Custom Sms Sent Successfully!');
    }

    public function edit($id)
    {
        $contactGroup = ContactGroup::query()->findOrFail($id);
        return view('smsgateway::contactGroup.edit',compact('contactGroup'));
    }

    public function show(ContactGroup $contactGroup)
    {
        return view('smsgateway::contactGroup.show',compact('contactGroup'));
    }

    public function update($id, Request $request)
    {
        $validator = Validator::make($request->all(),[
            
            'name'      => 'required|string',
        ]);
        $contactGroup= ContactGroup::query()->findOrFail($id);

        if($validator->fails()){
            return redirect()->back()->withErrors($validator)->withInput($request->all());
        }

        $contactGroup->update($request->all());
        return redirect()->route('contactGroup.index')->with('success', 'ContactGroup Updated Successfully!');
    }

    public function destroy($id)
    {
        $contactGroup = ContactGroup::query()->findOrFail($id);
        $contactGroup->delete();
        return redirect()->route('contactGroup.index')->with('success', 'ContactGroup Deleted Successfully!');
    }

}

Modules/SmsGateway/Resources/views/contactGroup/add.blade.php
@extends('smsgateway::layouts.master')

@section('title','Contact Group|WPM')

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h3>{{ __('Add ContactGroup') }}</h3>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">{{ __('Settings') }}</a></li>
                        <li class="breadcrumb-item active">{{__ ('contactGroup') }}</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <section class="content">
        @if($errors->any())
            <ul>
                @foreach($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        @endif
    </section>

    <!-- ***/Notices page inner Content Start-->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            {{ Form::model($contactGroup = new \Modules\SmsGateway\Entities\ContactGroup,['route'=>'contactGroup.store','method'=>'post']) }}
                            @include('smsgateway::contactGroup.form')
                            {{ Form::close() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@stop

Modules/SmsGateway/Resources/views/contactGroup/edit.blade.php
@extends('smsgateway::layouts.master')
@section('title','Contact Group|WPM')

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{ __('Edit ContactGroup') }}</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">{{__('Settings')}}</a></li>
                        <li class="breadcrumb-item active">{{__('Edit ContactGroup')}}</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <section class="content">
        @if($errors->any())
            <ul>
                @foreach($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        @endif
    </section>

    <!-- ***/Notices page inner Content Start-->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            {{ Form::model($contactGroup,['route'=>['contactGroup.update',$contactGroup->id],'method'=>'patch']) }}
                            @include('smsgateway::contactGroup.form')
                            {{ Form::close() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@stop

Modules/SmsGateway/Resources/views/contactGroup/form.blade.php
<div class="row">
    <div class="col-4"></div>
    <div class="col-4">
        <div class="form-group">
            <label for="name">Name*:</label>
            {{ Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Enter ContactGroup Name Here:']) }}
            <small class="text-danger">{{ $errors->first('name') }}</small>
        </div>
    </div>
    <div class="col-4"></div>
</div>
<div class="row">
    <div class="col-4"></div>
    <div class="col-4">
        <button type="submit" class="btn btn-success"> Create</button>
        <a href="{{ URL::previous() }}" class="btn btn-danger">Cancel</a>
    </div>
    <div class="col-4"></div>
</div>

Modules/SmsGateway/Resources/views/contactGroup/index.blade.php
@extends('smsgateway::layouts.master')
@section('title','Contact Group|WPM')

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{__('ContactGroups')}}</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">{{ __('Settings') }}</a></li>
                        <li class="breadcrumb-item active">{{__('contactGroups')}}</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>


    <!-- ***/Chart of Accounts page inner Content Start-->
    <section class="content">
        <div class="container-fluid">
            @if (session('status'))
                <div class="alert alert-success">
                    {{ session('status') }}
                </div>
            @endif
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header" style="border-bottom: none !important;">
                            <div class="row">
                                <div>
                                    <a href="{{ route('contactGroup.create') }}" class="btn btn-info btn-sm" style="margin-top: 10px; margin-left: 10px;"> <i class="fas fa-plus-circle"></i> New</a>
                                </div>
                            </div>
                        </div>

                        <div class="card-body">
                            <table id="example2" class="table table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>{{ __('Sl') }}</th>
                                    <th>{{ __('Name') }}</th>
                                    <th>{{ __('Contacts Available') }}</th>
                                    <th>{{ __('Action') }}</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($contactGroups as $key => $data)
                                    <tr>
                                        <td>{{ $key+1 }}</td>
                                        <td>{{ $data->name }}</td>
                                        <td>{{ $data->contacts_count }}</td>
                                        <td>
                                            
                                            {{ Form::open(['url'=>['admin/contactGroup',$data->id],'method'=>'delete','onsubmit'=>'return confirmDelete()']) }}
                                            <a href="{{ route('contactGroup.show',$data->id) }}" class="btn btn-info btn-sm"><i class="fas fa-eye"></i></a>
                                            <a href="{{ route('contactGroup.edit',$data->id) }}" class="btn btn-warning btn-sm"><i class="fas fa-edit"></i></a>
                                            <button type="submit" class="btn btn-danger btn-sm"><i class="fas fa-trash"></i></button>
                                            {{ Form::close() }}
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                            <div class="row" style="margin-top: 10px">
                                <div class="col-sm-12 col-md-9">
                                    {{-- <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">Showing 0 to 0 of 0 entries</div> --}}
                                </div>
                                <div class="col-sm-12 col-md-3">
                                    {{ $contactGroups->links() }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

@stop

@section('script')
    <script>
        function confirmDelete(){
            let x = confirm('Are you sure you want to delete this account head?');
            return !!x;
        }
    </script>
@stop

Modules/SmsGateway/Resources/views/contactGroup/show.blade.php
@extends('smsgateway::layouts.master')

@section('title','Contact Group|WPM')

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{$contactGroup->name}}</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">{{ __('Settings') }}</a></li>
                        <li class="breadcrumb-item active">{{__('contactGroups')}}</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>


    <!-- ***/Chart of Accounts page inner Content Start-->
    <section class="content">
        <div class="container-fluid">
            @if (session('status'))
                <div class="alert alert-success">
                    {{ session('status') }}
                </div>
            @endif
            <div class="row">
                <div class="col-12">
                    <div class="card">

                        <div class="card-body">
                            <table id="example2" class="table table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>{{ __('Sl') }}</th>
                                    <th>{{ __('Name') }}</th>
                                    <th>{{ __('Contact Number') }}</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($contactGroup->contacts as $key => $data)
                                    <tr>
                                        <td>{{ $key+1 }}</td>
                                        <td>{{ $data->name }}</td>
                                        <td>{{ $data->number }}</td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                            <div class="row" style="margin-top: 10px">
                                <div class="col-sm-12 col-md-9">
                                    {{-- <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">Showing 0 to 0 of 0 entries</div> --}}
                                </div>
                                <div class="col-sm-12 col-md-3">
                                    {{-- {{ $contactGroup->links() }} --}}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

@stop

@section('script')
    <script>
        function confirmDelete(){
            let x = confirm('Are you sure you want to delete this account head?');
            return !!x;
        }
    </script>
@stop